# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carrot-Market' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carrot-Market
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'BSImagePicker', '~> 3.1' 
  pod 'NMapsMap'
  pod 'SnapKit', '~>5.6.0'
end
